### DISCUSSION TITLE
author_info and device_info.xml setup

### DISCUSSION THREAD

**Discussion by noiwontsmile** [philosowaffle/peloton-to-garmin#117] [Q&A] [answered]
I followed the instructions on creating the author_info.xml and device_info.xml but the data doesn't appear to be showing up in the resulting *.txc files.  I also do not have any device info showing up in the activity upon upload to Garmin.  I'm using p2g1.2.0 with Docker (first time using docker!).  Both xml files are located in the main p2g directory.  Is there something else that I could be missing that I can look into?

**Comment by philosowaffle** [comment, marked as answer]
You likely need to mount these files so they are accessible in the Docker container.  The docker container is a completely isolated file system so it does not have access to anything unless you give it access.

Just off the top of my head, I think you will want something like this:
```
version: "3.5"
   
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin
    environment:
      - P2G_PELOTON_EMAIL=peloton@gmail.com
      - P2G_PELOTON_PASS=peloton_password
      - P2G_GARMIN_ENABLE_UPLOAD=true
      - P2G_GARMIN_EMAIL=garmin@gmail.com
      - P2G_GARMIN_PASS=garmin_password
      - P2G_NUM=4
      - PTG_POLLING_INTERVAL_SECONDS=3600 # 1hr
      # additional environment vars can be configured here
    volumes:
      - ./logs:/logs
      - ./output:/output
      - ./author_info.xml:/opt/app/author_info.xml  # these two lines should mount the files in the container
      - ./device_info.xml:/opt/app/device_info.xml
```

In the volumes section, the syntax is `/local/path/to/something:/where/that/thing/should/live/in/the/container`
