### DISCUSSION TITLE
Fixed "localhost" issue on macOS

### DISCUSSION THREAD

**Discussion by GasMD** [philosowaffle/peloton-to-garmin#313] [Show and tell]
Just wanted to share how I configured on macOS to get the new api/webui images running successfully through docker.  Hope this saves another Mac user some setup time in the future. I was persistently receiving an error about localhost:

> Unable to bind to http://localhost:80 on the IPv6 loopback interface: 'Cannot assign requested address'

I read through another set of posts regarding setup on a Synology server and used the same configuration to get everything working.

My docker-compose.yaml (key changes are the addition of ports.  Only other change from default/example file is my time zone):

```
version: "3.9"

services:
  p2g-api:
    container_name: p2g-api
    image: philosowaffle/peloton-to-garmin:api-latest
    environment:
      - TZ=America/New_York
    ports:
      - 8001:8080
    volumes:
      - ./api.local.json:/app/configuration.local.json
      - ./data:/app/data # recommended for saving settings across restarts
      - ./output:/app/output # optional, if you want access to the generated workout and log files
  
  p2g-webui:
    container_name: p2g-webui
    image: philosowaffle/peloton-to-garmin:webui-latest
    ports:
      - 8002:8080
    environment:
      - TZ=America/New_York
    volumes:
      - ./webui.local.json:/app/configuration.local.json
    depends_on:
      - p2g-api
```

My api.local.json (key addition is the change to HostUrl:
```
{
"Api": {
      "HostUrl": "http://*:8080"
    },
    
"Observability": {
  
      "Prometheus": {
        "Enabled": false,
        "Port": 4000
      },
  
      "Jaeger": {
        "Enabled": false,
        "AgentHost": "localhost",
        "AgentPort": 6831
      },
  
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": "Information",
        "WriteTo": [
          { "Name": "Console" },
          {
            "Name": "File",
            "Args": {
              "path": "./output/log.txt",
              "rollingInterval": "Day",
              "retainedFileCountLimit": 7
            }
          }
        ]
      }
    }
  }
```

My webui.local.json (key addition are the two HostUrl changes):
```
{
  
  "Api": {
      "HostUrl": "http://p2g-api:8080"
    },

  "WebUI": {
      "HostUrl": "http://*:8080"
    },
  
    "Observability": {
  
      "Prometheus": {
        "Enabled": false,
        "Port": 4000
      },
  
      "Jaeger": {
        "Enabled": false,
        "AgentHost": "localhost",
        "AgentPort": 6831
      },
  
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
        "MinimumLevel": "Information",
        "WriteTo": [
          { "Name": "Console" },
          {
            "Name": "File",
            "Args": {
              "path": "./output/log.txt",
              "rollingInterval": "Day",
              "retainedFileCountLimit": 7
            }
          }
        ]
      }
    }
  }
```
Once those files are in the same directory:
<img width="560" alt="image" src="https://user-images.githubusercontent.com/112187847/186935655-d2574a43-25a3-489a-94fd-7b0f914a8b41.png">

A simple 

> docker-compose up

command run in that directory should yield success.  You'll be able to access the webui at http://localhost:8002/ 
Hope this saves someone time and effort!
