### DISCUSSION TITLE
Question on sync for multiple accounts on the same Linux machine (if feasable)

### DISCUSSION THREAD

**Discussion by BowmanRA** [philosowaffle/peloton-to-garmin#365] [Q&A] [answered]
Good day,

This project is amazing - thank you so much.

Is there a recommended way of running the sync system on the same machine (Linux, via Docker) for multiple accounts please?

I have my own Peloton -> Garmin working fine using the UI. This is on an Ubuntu server. It works /really/ well.

Just struggling to fathom how I might set-up a second instance (for my wife).

I've pulled into a separate folder. I tried a few things in docker-compose.yaml. Namely something like ...

```
version: "3.9"

services:
  p2g-api-ab:
    container_name: p2g-api-ab
    image: philosowaffle/peloton-to-garmin:api-stable
    environment:
      - TZ=America/Chicago
    #ports:
    #   - 8003:8081 # optional, only if you plan to interact with the API directly
    volumes:
      - ./api.local.json:/app/configuration.local.json
      - ./data:/app/data # recommended for saving settings across restarts
      - ./output:/app/output # optional, if you want access to the generated workout and log files
  
  p2g-webui-ab:
    container_name: p2g-webui-ab
    image: philosowaffle/peloton-to-garmin:webui-stable
    ports:
      - 8004:8081
    environment:
      - TZ=America/Chicago
    volumes:
      - ./webui.local.json:/app/configuration.local.json
    depends_on:
      - p2g-api-ab

```

... where I've shifted up the port numbers. Generally - a little tinkering in there.

I spin up the image and it reports all's fine ...

```
`Creating network "p2g-webui-ab_default" with the default driver
Creating p2g-api-ab ... done
Creating p2g-webui-ab ... done`
```

... and I can display the webui on port 8004. However, I get this message on the UI when I visit it @ port 8004 ...

`Failed to fetch Sync status - Call failed. Resource temporarily unavailable (p2g-api:8081): GET http://p2g-api:8081/api/sync - See logs for details.
Failed to fetch data from P2G Api - Call failed. Resource temporarily unavailable (p2g-api:8081): GET http://p2g-api:8081/api/settings - See logs for details.`

... I guess because I've muddled up spinning up the API on 8081.

I had tried pointing to the regular API on 8080 but I couldn't then get anything on port 8004.

Thank you for any thoughts on how to achieve additional sync services. If that's possible. Maybe it's not possible and I need a 2nd machine? 

Brilliant project - why Peloton can't just sync to Garmin themselves is beyond me. But, hey ho. Thanks to the community there is a solution!

Regards
Robert

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

api.local.json
```
{
  "Api": {
    "HostUrl": "http://*:8081"
  },

  "Observability": {

    "Prometheus": {
      "Enabled": false
    },

    "Jaeger": {
      "Enabled": false,
      "AgentHost": "localhost",
      "AgentPort": 6831
    },

    "Serilog": {
      "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
      "MinimumLevel": {
        "Default": "Information",
        "Override": {
          "Microsoft": "Error",
          "System": "Error"
        }
      },
      "WriteTo": [
        { "Name": "Console" },
        {
          "Name": "File",
          "Args": {
            "path": "./output/log.txt",
            "rollingInterval": "Day",
            "retainedFileCountLimit": 7
          }
        }
      ]
    }
  }
}
```


webui.local.json
```
{
  "Api": {
    "HostUrl": "http://p2g-api:8081"
  },

  "WebUI": {
    "HostUrl": "http://*:8081"
  },

  "Observability": {

    "Prometheus": {
      "Enabled": false
    },

    "Jaeger": {
      "Enabled": false,
      "AgentHost": "localhost",
      "AgentPort": 6831
    },

    "Serilog": {
      "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.File" ],
      "MinimumLevel": {
        "Default": "Information",
        "Override": {
          "Microsoft": "Error",
          "System": "Error"
        }
      },
      "WriteTo": [
        { "Name": "Console" },
        {
          "Name": "File",
          "Args": {
            "path": "./output/log.txt",
            "rollingInterval": "Day",
            "retainedFileCountLimit": 7
          }
        }
      ]
    }
  }
}
```

**Comment by philosowaffle** [comment, marked as answer]
Great question, looking through your setup, I think the problem is you've got some Ports misconfigured and your WebUI config is still trying to talk to the wrong P2G Api container name.

There are a couple different ways to organize your docker containers for multi-user P2G, but I prefer the below approach as it keeps things organized, segregated, and not overly complex. (this sounds like the approach you were already attempting to do 😃  )

Here is how I have mine setup, hosting for a few family members:

## folder structure
```text
- p2g/
  | user1/
     | data/
     | api.config.json
     | webui.config.json
     | docker-compose.yaml
  | user2/
     | data/
     | api.config.json
     | webui.config.json
     | docker-compose.yaml
```

## user1 docker-compose

```yaml
p2g-api-user1:
    container_name: p2g-api-user1
    image: philosowaffle/peloton-to-garmin:api-stable
    environment:
      - TZ=America/Chicago
    volumes:
      - ./api.config.json:/app/configuration.local.json
      - ./data:/app/data
      - ./data:/app/output
  
 p2g-web-user1:
    container_name: p2g-web-user1
    image: philosowaffle/peloton-to-garmin:webui-stable
    ports:
      - 8003:8080
    environment:
      - TZ=America/Chicago
    volumes:
      - ./webui.config.json:/app/configuration.local.json
   depends_on:
      - p2g-api-user1
```

## user1 Api Config File

```json
{
  "Api": {
    "HostUrl": "http://*:8080"
  },

  .... truncated Observability section....
}
```

## user1 Web Config File

```json
"Api": {
    "HostUrl": "http://p2g-api-user1:8080"  <----- I think this is where you're having trouble right now, your second user needs to point to the right p2g api instance
  },

  "WebUI": {
    "HostUrl": "http://*:8080"
  },

  .... truncated Observability section....
```

## user2 docker-compose

This is identical to user1 with only two small changes:
1. Give the containers a unique name for user2
2. Give the WebUI a unique port

```yaml
p2g-api-user2:
    container_name: p2g-api-user2
    image: philosowaffle/peloton-to-garmin:api-stable
    environment:
      - TZ=America/Chicago
    volumes:
      - ./api.config.json:/app/configuration.local.json
      - ./data:/app/data
      - ./data:/app/output
  
 p2g-web-user2:
    container_name: p2g-web-user2
    image: philosowaffle/peloton-to-garmin:webui-stable
    ports:
      - 8004:8080 # using 8004 now, since user1 is using 8003
    environment:
      - TZ=America/Chicago
    volumes:
      - ./webui.config.json:/app/configuration.local.json
   depends_on:
      - p2g-api-user2
```


## user2 Api Config File

Identical to user1 Api config, no changes.

## user2 Web Config File

```json
"Api": {
    "HostUrl": "http://p2g-api-user2:8080"  <----- make sure we're pointing to the user2 api, we're using the container name to ensure this
  },

  "WebUI": {
    "HostUrl": "http://*:8080"
  },

  .... truncated Observability section....
```

## Conclusion

Now,
* user1 should be able to reach the webui on port `8003`
* user2 should be able to reach the webui on port `8004`
