### ISSUE TITLE
[Feature] Security - Change docker container to not run as Root user.

### ISSUE THREAD

**Issue by philosowaffle** [philosowaffle/peloton-to-garmin#185]
**Acceptance Criteria:**
1. The docker container should not run as root user.
2. The docker container should run as user id: `1030`
3. Update documentation to share this info, this user will need read/write permissions to certain directories

**Comment by philosowaffle** [comment]
Verified, you can achieve this by simply using the User param with either docker run or docker compose:

```
version: "3.5"
   
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin
    user: 1030:1010
    command: "web"
    ports:
      - 80:80
    environment:
      - TZ=America/Chicago
    volumes:
      - ./configuration.local.json:/app/configuration.local.json
```
