### ISSUE TITLE
[Feature] Home Assistant Integration Feature request

### ISSUE THREAD

**Issue by neildsb** [philosowaffle/peloton-to-garmin#467]
It would be great to have a Home Assistant (HACS https://github.com/hacs) integration to work with https://github.com/edwork/homeassistant-peloton-sensor (a great integration for triggering fans, lights, etc) when a workout has been completed it triggers Peloton-to-Garmin to upload the workout :-).

**Comment by philosowaffle** [comment]
Good news, I have laid some ground work to prep for this kind of request.  And currently, I'm thinking a full fledged new integration may be overkill.

If homeassistant-peloton-sensor would be willing to add support for additionally exposing the WorkoutId for the last workout completed, then that could easily be used to call an existing REST API endpoint on P2G using Home Assistant's [REST Command integration](https://www.home-assistant.io/integrations/rest_command/).

Assuming, homeassistant-peloton-sensor would be willing/able to expose that information, then your script would look something like this:

```
// assume some trigger has occurred from homeassistant-peloton-sensor to indicate end of workout

rest_command:
  sync_request:
   url: "http://<your-p2g-api>/api/sync"
   method: post
   content_type: 'application/json; charset=utf-8'
   payload: '{"workoutIds":[ "{{workoutId}}" ]}
```

You can find all of the available API endpoints at the following url for your instance:
http://<your-p2g-api>/swagger/index.html
