### ISSUE TITLE
Not reading ini file

### ISSUE THREAD

**Issue by gigaguy** [philosowaffle/peloton-to-garmin#89]
I ran the docker and tried using the ini file rather than the env vars.  It appears to accept some like the peloton login, but it seems to ignore most of the rest.  It didn't upload to garmin or accept the poll interval despite it being set and uncommented in the ini. Any ideas?

**Comment by philosowaffle** [comment]
Might double check you are mounting the .ini file to the correct location.  Quick compose example:

```
version: "3.5"
   
services:
  p2g:
    container_name: p2g
    image: philosowaffle/peloton-to-garmin
    volumes:
      - ./logs:/logs
      - ./output:/output
      - ./config.local.ini:/opt/app/config.local.ini
```

Disclaimer: This is a guess. I've only ever tested the Docker container using the ENV vars. In theory this should work though.
